// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $cart from "./routes/cart.tsx";
import * as $category_name_ from "./routes/category/[name].tsx";
import * as $counter from "./routes/counter.tsx";
import * as $gallery from "./routes/gallery.tsx";
import * as $index from "./routes/index.tsx";
import * as $notes from "./routes/notes.tsx";
import * as $product from "./routes/product.tsx";
import * as $search from "./routes/search.tsx";
import * as $partials_menu from "./routes/partials/menu.tsx";
import * as $JsCounter from "./islands/JsCounter.tsx";
import * as $Menu from "./islands/Menu.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/cart.tsx": $cart,
    "./routes/category/[name].tsx": $category_name_,
    "./routes/counter.tsx": $counter,
    "./routes/gallery.tsx": $gallery,
    "./routes/index.tsx": $index,
    "./routes/notes.tsx": $notes,
    "./routes/product.tsx": $product,
    "./routes/search.tsx": $search,
    "./routes/partials/menu.tsx": $partials_menu,
  },
  islands: {
    "./islands/JsCounter.tsx": $JsCounter,
    "./islands/Menu.tsx": $Menu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
